---

- name: Add VSCode repo using key from URL
  ansible.builtin.deb822_repository:
    name: vscode
    types: [deb]
    uris: "https://packages.microsoft.com/repos/code"
    architectures: [amd64, arm64, armhf]
    components: [main]
    suites: [stable]
    signed_by: https://packages.microsoft.com/keys/microsoft.asc
    state: present
    enabled: true

- name: Remove old vscode.list file
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/vscode.list
    state: absent
  become: true
  become_user: root
