---
- name: Remove legacy apt file
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/vscode.list
    state: absent

- name: Add VSCode repo using key from URL
  ansible.builtin.deb822_repository:
    name: vscode
    types: [deb]
    uris: "http://packages.microsoft.com/repos/code"
    architectures: [amd64, arm64, armhf]
    components: [main]
    suites: [stable]
    signed_by: https://packages.microsoft.com/keys/microsoft.asc
    state: present
    enabled: true

- name: Install VSCode
  ansible.builtin.apt:
    name: code
    update_cache: true
    state: present
